### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#37]
- [ ] add a X "clear input" symbol at the end of the input line
- [ ] fold also "GitHub" and "Kontact" into "Über" (to save screen space)
- [ ] extend space between the "play" and "download" icons (allow more space: on smartphones, the both are too close, and clicking on is difficult)

(I am going to install the software on my server an will try to fix one or the other and come back later with formal issues, and/or pull requests.). Feel free to extend this "Sammeleintrag".)

**Comment by bagbag** [comment]
Am I also allowed to fix these? :P 

Point 1: good idea 👍 
Point 2: The navbar will just get empty, but we won't save any space?
Point 3: So only extend space on small screens and leave it like it is on desktop?
Point 4: 👍

**Comment by Wikinaut** [comment]
> allowed to fix:
Klaro!
ad 2: looks much better. Average user does not even know what "GitHub" means. Perhaps also rename the button to "Sourcecode" or so. (I will add this in a second)

ad 3: add one additional `&nbsp;` on all screens (as a quick fix. Should help. Did not test it. I just building my build-environment...)

**Comment by bagbag** [comment]
clear button implemented: 8805318e80906c5befc88e7ae0e77f3a910d47ff

**Comment by bagbag** [comment]
label tag implemented: 655202aee5ee715fe3bd860cc0926aebfa00e3bd

**Comment by bagbag** [comment]
space extended: b472f2abf22df0d057d18afb045f7c3472f88ef0 (but not much, as it doesn't look good than)

**Comment by Wikinaut** [comment]
regarding point 2: I noticed, that on my mobile phone, all these items are "under" a three-bar icon, which looks fine.

**Comment by bagbag** [comment]
so your intention of that was because of small screens?

**Comment by Wikinaut** [comment]
It was... both! On my small device I noticed, that my "wish" was magically fulfilled, and on the larger  MacBook screen, I wish to have *all* unnecessary links hidden. And you could also move "Hilfe" to the button.

It's not a "must have", it's a wish.
